[project]
name = "assignment"
version = "0.1.0"
description = "CS 768 Assignment"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "pyyaml>=6.0.2",
    "torch>=2.6.0",
]
