line-length = 99

[lint]
extend-select = ["E501"]

[lint.per-file-ignores]
"__init__.py" = ["E402"]
"scripts" = ["D"]

[lint.pydocstyle]
convention = "google"

[format]
preview = true
docstring-code-format = true
